### ISSUE TITLE
Failing build on local machine for 0.6.11-rc staging branch

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket-js-LEGACY#398]
**Describe the bug**
Non-passing build after fresh `pull` and `npm install`

**To Reproduce**
1. Go to the repository clone on your machine
2. run `npm run build`
3. Depending on your machine, go get coffee or get ready for the results
4. See errors(zzz)
````
╰─$ src/pocket.ts:60:31 - error TS2345: Argument of type 'IRPCProvider | undefined' is not assignable to parameter of type 'IRPCProvider'.
  Type 'undefined' is not assignable to type 'IRPCProvider'.

60       this.innerRpc = new RPC(rpcProvider)
                                 ~~~~~~~~~~~

src/pocket.ts:275:82 - error TS2339: Property 'message' does not exist on type 'Error | Buffer'.
  Property 'message' does not exist on type 'Buffer'.

275         return new RpcError("NA", "Error signing Relay proof: "+signatureOrError.message)
                                                                                     ~~~~~~~

src/pocket.ts:325:17 - error TS2345: Argument of type 'Session | undefined' is not assignable to parameter of type 'Session'.
  Type 'undefined' is not assignable to type 'Session'.

325                 rpcError.session,
                    ~~~~~~~~~~~~~~~~

src/pocket.ts:392:54 - error TS2345: Argument of type 'RelayResponse | RpcError' is not assignable to parameter of type 'RelayResponse'.
  Type 'RpcError' is missing the following properties from type 'RelayResponse': signature, payload, proof, relayRequest, isValid

392         return new ConsensusNode(serviceNode, false, result)
                                                         ~~~~~~


Found 4 errors.

````

**Expected behavior**
Build to pass

**Screenshots**
![Screenshot from 2021-04-28 03-47-34](https://user-images.githubusercontent.com/13497307/116343893-df86f080-a7d4-11eb-9297-94dabc272da5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser: irrelevant
 - Version: node v14

**Comment by pabelnl** [comment]
This is related to the node version not being supported, pocket-js recommended node version is 12.15, change your node version and do a fresh `pull`, `npm install` and then `npm run build`

**Comment by Evalir** [comment]
Regarding the node versions supported, what is holding us back from bumping the max version up from 12.15? Node 12 is on-track to be deprecated about a [year from now](https://endoflife.software/programming-languages/server-side-scripting/nodejs), and node 10 [has already been deprecated](https://vercel.com/changelog/node-js-10-is-being-deprecated).

**Comment by pabelnl** [comment]
It is related to a library called amino-js that doesn't even support 12.15, we did our own fork and added support up to 12.15, this amino-js library will be eliminated after pocket-core migration to protobuf is complete in production, at that point we can remove this library and support newer versions of node.
